apiVersion: v1
kind: Service
metadata:
  name: food-ordering-service
spec:
  type: NodePort
  selector:
    app: food-ordering-app
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30001
